"""update the students table

Revision ID: fc00fee8709d
Revises: ebb4363b394a
Create Date: 2025-08-14 18:14:49.704557

"""
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc00fee8709d'
down_revision: Union[str, None] = 'ebb4363b394a'
branch_labels = None
depends_on = None

# Create the enum type first
tags_enum = sa.Enum(
    'Students not contacted in 7 days',
    'High intent',
    'Needs essay help',
    name='tags'
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    tags_enum.create(op.get_bind())

    # Add new columns (example: adding a 'status' column)
    op.add_column('students', sa.Column('tags', sa.String(), nullable=True))

    # Modify the tags column to use the enum
    op.alter_column('students', 'tags',
               existing_type=sa.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(tags_enum),
               postgresql_using="tags::tags_enum[]",
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Revert the tags column modification
    op.alter_column('students', 'tags',
               existing_type=sa.ARRAY(tags_enum),
               type_=sa.ARRAY(sa.TEXT()),
               postgresql_using="tags::text[]",
               existing_nullable=True)

    # Drop the new column
    op.drop_column('students', 'status')

    # Drop the enum type
    tags_enum.drop(op.get_bind())
    ### end Alembic commands ###